apiVersion: v1
kind: PersistentVolume
metadata:
  name: rwx-nfs-pv
  labels:
    lab: rwx-nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 172.16.0.5
    path: /srv/k8s-rwx
