apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-nfs-claim
  namespace: rwx-lab
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs-static
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      lab: rwx-nfs
