apiVersion: v1
kind: ResourceQuota
metadata:
  name: label-lab-quota
  namespace: label-lab
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: 2Gi
    limits.memory: 4Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "5"
    pods: "10"
