apiVersion: v1
kind: Pod
Metadata:
  name: struck-pod
  namespace: default
  finalizers:
     - ://example.com
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      lifecycle:
        prestop:
          exec:
            command: ["/bin/sh", "-c", "sleep 3600"]


#kubectl delete pod test-stuck-pod --wait=false