apiVersion: v1
kind: Pod
Metadata:
  name: impossible-cpu-load
spec:
   containers:
   - name: heavy-app
     image: busybox
     command: ["sleep", "3600"]
     resources:
       requests:
         cpu: "1000"