apiVersion: v1
kind: Pod
Metadata:
  name: production
  labels:
    app: core-api
    tier: production
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 60
  containers:
   - name: api-server
     image: nginx:alpine
     lifecycle:
       preStop:
       exec:
         command: ["/bin/sh", "-c", "sleep 15; nginx -s quit"]

     startupProbe:
       httpget:
         path: /healthz
         port: 80
       initialDelaySeconds: 5
       periodSeconds: 5
       failureThreshold: 20

     livenessProbe:
        httpget:
          path: /healthz
          port: 80
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3
     readinessProbe:
        httpGet: 
           path: /healthz
           port: 80
        periodSeconds: 5
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 2
