apiVersion: v1
kind: Pod
metadata:
   name: multi-container-life
spec: 
   restartPolicy: Never
   initContainers:
    - name: init-task
      image: busybox
      command:  ["/bin.sh", "-c"]
      args:
      - > 
        echo "[$(date +%T)] INIT CONTAINER: Starting initialization tasks...";
        sleep 5;
        echo "[$(date +%T)] INIT CONTAINER: Database/schema check complete. Exiting cleanly.";
   containers:
    - name: main-app
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
      - > 
        echo "[$(date +%T)] MAIN APP: Web server initializing...";
        sleep 3;
        echo "[$(date +%T)] MAIN APP: Handling traffic. Task complete.";

    - name: sidecar-logger
      image: busybox
      command: ["/bin.sh", "-c"]
      args: 
      - >
         echo "[$(date +%T)] SIDECAR: Log forwarder agent started...";
          sleep 3;
          echo "[$(date +%T)] SIDECAR: Sync complete.";